### ISSUE TITLE
Make navbar and footer 

### ISSUE THREAD

**Issue by rohansx** [open-xyz/doctalyzer#4]
Make navbar and footer for this

**Comment by tiwariParth** [comment]
I would like to contribute!.
What package manager it is using tho?

**Comment by rohansx** [comment]
@Bingolast it's all yours. It is using npm

**Comment by Bingolast** [comment]
> @Bingolast it's all yours. It is using npm

well i tried but its showing compiling error
![image](https://user-images.githubusercontent.com/99398053/233845172-eec30900-e4ab-4423-b753-6aefda81c2d9.png)

**Comment by tiwariParth** [comment]
> > @Bingolast it's all yours. It is using npm
> 
> well i tried but its showing compiling error ![image](https://user-images.githubusercontent.com/99398053/233845172-eec30900-e4ab-4423-b753-6aefda81c2d9.png)
Am i doing anything wrong here?
I did npm install and then npm run

**Comment by rohansx** [comment]
@Bingolast It is working fine in my system.
Ig it might be due to dotenv dependency
Try "npm install dotenv" and if it still occurs try pasting the whole error to chatgpt

**Comment by rohansx** [comment]
@Bingolast hey does that issue resolved?

**Comment by tiwariParth** [comment]
> @Bingolast hey does that issue resolved?
> 

I'm afraid no 🥲
I even tried installing dependency.
I actually want to try it using vite

**Comment by tiwariParth** [comment]
Heyy I asked about this issue in some communities they are also facing same issue

**Comment by rohansx** [comment]
@Bingolast I'll try to solve this issue and will let you know tomorrow

**Comment by tiwariParth** [comment]
> @Bingolast I'll try to solve this issue and will let you know tomorrow

heyy is it solved

**Comment by rohansx** [comment]
@Bingolast couldn't able to solve, I'm thinking to rebuild this.
Do you have any suggestions?

**Comment by tiwariParth** [comment]
> @Bingolast couldn't able to solve, I'm thinking to rebuild this.
> Do you have any suggestions? 

Yess!! Building it using vite will solve this issue ig 
Because that's what product managers are

**Comment by rohansx** [comment]
@Bingolast can you do this ?

**Comment by tiwariParth** [comment]
suree!! i will give it a try

**Comment by rohansx** [comment]
Ok then, will be waiting for your PR.

**Comment by tiwariParth** [comment]
heyy!! I tried but sorry I was unable to figure out how to do it. The traditional way of building it from scratch isn't working.
I copied all the files but dev server was not booting up. Do I need to configure manually something ?

**Comment by tiwariParth** [comment]
should i unassign myself?

**Comment by rohansx** [comment]
@Bingolast ok no issue, I will build it myself. 
Btw would love if you join this organization so that you can further contribute to this.

**Comment by tiwariParth** [comment]
> @Bingolast ok no issue, I will build it myself. 
> Btw would love if you join this organization so that you can further contribute to this. 

That would be amazing 🤩
I would love to be a part of it

**Comment by rohansx** [comment]
I have invited you.
Feel free to create project if you have any idea

**Comment by tiwariParth** [comment]
umm where can i see invites?

**Comment by rohansx** [comment]
Check into the invitation

**Comment by k-deepak04** [comment]
@rohansx is the issue still there
can i make navbar and footer?

**Comment by rohansx** [comment]
Need to build this project from scratch..
I'm just engaged in some other things so will start building it again from next week.

**Comment by tiwariParth** [comment]
> Need to build this project from scratch..
> I'm just engaged in some other things so will start building it again from next week.
> 

Heyy! I can help with it I just want to know if we are going to use the same code ? 
And this project can be containerised using docker so that it will create and install all the dependencies when someone tries to run it on there local machines

**Comment by rohansx** [comment]
Hello! Thank you for offering to help. You are free to build the project from scratch if you prefer. As for containerization, using Docker to package and distribute the project with all its dependencies is a great idea. It will make it easier for others to run the project on their local machines without worrying about installing dependencies. If you are comfortable with Docker, I encourage you to proceed with containerizing the project.
