### ISSUE TITLE
Create README.md file

### ISSUE THREAD

**Issue by rohansx** [open-xyz/doctalyzer#5]
Create Readme.md file and fill relevant content according to this project

**Comment by Frenziecodes** [comment]
Hey @rohansx  I would love to work on this issue

**Comment by rohansx** [comment]
@lewisushindi go on

**Comment by Frenziecodes** [comment]
@rohansx, could you please provide me with information about all the available features currently  so that I don't miss including any of them in the README file?

**Comment by rohansx** [comment]
As the project is in initial stage so there is not much features implemented for now.
But as the name and description suggest you can make accordingly.
Here are some features this web app consist of.. 
 -Upload medical reports in various formats (PDF, JPG, PNG, etc.)
-Extract text from uploaded reports using Tesseract.js OCR engine
-Interpret medical reports in simple language using the ChatGPT API

Feel free to add if you think anything is relevant.

**Comment by Frenziecodes** [comment]
@rohansx  Please review pull #7 and let me know if you have any further changes that you would like me to make.

**Comment by rohansx** [comment]
Everything looks good
@lewisushindi thanks for your contribution

**Comment by rohansx** [comment]
Everything looks good
@lewisushindi thanks for your contribution

**Comment by rohansx** [comment]
Also, would love if you join in this organization and contribute to this organization
